name: fileToTo
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run a multi-line script
        run: |          

          set -x

          done_line=`cat files.done`
          next_line=$(($done_line + 1)) 

          mkdir tmpdir
          cd tmpdir


          for file in `tail -n +$next_line ../files.list`
          do
            # -r: 递归下载。
            # -np: 不要上溯到父目录。
            # --cut-dirs=1: 忽略 URL 的第一级目录。
            # -x: 强制创建目录结构。
            wget -r -np --cut-dirs=1 -x $file
          done


          cd ..
          # 处理完成后，需要更新 files.done 文件行数
          wc -l files.list|awk '{print $1}' > files.done


          datetime=`date +%Y%m%d%H%M%S`
          tar -czvf ${datetime}.tgz -C tmpdir .

          wget -q -O ossutil-2.0.6-beta.01091200-linux-amd64.zip  https://gosspublic.alicdn.com/ossutil/v2-beta/2.0.6-beta.01091200/ossutil-2.0.6-beta.01091200-linux-amd64.zip
          unzip ossutil-2.0.6-beta.01091200-linux-amd64.zip &&  chmod +x ossutil-2.0.6-beta.01091200-linux-amd64/ossutil

          ls -lh
          pwd

          #./ossutil-2.0.6-beta.01091200-linux-amd64/ossutil --access-key-id ${{ secrets.ALIYUN_CYG_OSS_AK }}  --access-key-secret ${{ secrets.ALIYUN_CYG_OSS_SK }}  --endpoint ${{ secrets.ALIYUN_CYG_OSS_ENDPOINT }} --region ${{ secrets.ALIYUN_CYG_OSS_REGION }}  cp -f ${datetime}.tgz oss://cncfstack-filetoto/

